### ISSUE TITLE
not an issue realpath.c

### ISSUE THREAD

**Issue by cucurbita** [averell23/zsh_averell#1]
I am the author 8-)

**Comment by cucurbita** [comment]
I fixed it : https://raw.githubusercontent.com/cucurbita/Inutero/master/realpath/realpath.c

**Comment by averell23** [comment]
@cucurbita could you actually some open source license in realpath.c ? at the moment it says "all rights reserved", so I would actually not legally be able to use it.

**Comment by cucurbita** [comment]
yes,  you are ; it's "all reserved as author, intellectual properties" ; the license is New BSD see read-me ; then you do whatever you want util you keep the author ;

**Comment by cucurbita** [comment]
@averell23 New BSD licensed. @see root repo. 

Hello I moved it again here:

https://github.com/cucurbita/MoreMacCommands/tree/master/realpath

- added an option : -escaped or nothing (escapes white-spaces)
```
usage: realpath a_path or realpath -escaped  a_path
```
- saved some dyn-allocs by reusing static buffer ; should speed-up a bit the cmd, might make a difference on thousands calls. 

- best
